### ISSUE TITLE
BPCell instalation with new GitHub path

### ISSUE THREAD

**Issue by GischD** [bnprks/BPCells#105]
Dear BPCell team,

Thank you for developing the BPCell package.
I installed the package using the old GitHub path with renv. 
After BPCell moved to the new folder I am getting the following error.

```
Error: Error installing package 'BPCells':
===================================

* installing *source* package ‘BPCells.installation.moved’ ...
** using staged installation
ERROR: 'configure' exists but is not executable -- see the 'R Installation and Administration Manual'
```

Would you happen to have an idea of what is causing the issue?

Thank you,
Debora

**Comment by bnprks** [comment]
Hi Debora,

Thanks for your question. As I commented on your [issue in the renv repo](https://github.com/rstudio/renv/issues/1941) this does appear to be related to an renv bug. You should be able to work around it a bit by running `remotes::install_github("bnprks/BPCells/r")` from within your renv environment. 

That might miss out on some renv features, but I'm pretty sure it will install the package into your local environment correctly.

The fact that you got the `'configure' exists but is not executable` error is a problem on the BPCells side, but even with that fixed you'll still get an error while running `renv::install("bnprks/BPCells:r")`.

-Ben

**Comment by GischD** [comment]
Hi Ben,

Thank you for your effort in figuring out what is happening. 
I installed it with remotes, and it works.

Debora
