### ISSUE TITLE
Get 'undefined symbol' error when build the package

### ISSUE THREAD

**Issue by ycli1995** [bnprks/BPCells#109]
Hi, @bnprks. I try to add linear regression as new feature for BPCells, so I create a branch here: https://github.com/ycli1995/BPCells/tree/LinearResidual

However, when I tested the package using `devtools::document()`, the compiler seemed to ignore the `LinearResidual.cpp` I created, and raise an error:
```
Error in dyn.load(dll_copy_file) : 
  unable to load shared object '/tmp/RtmpTdktzr/pkgload11b0251da3c23/BPCells.so':
  /tmp/RtmpTdktzr/pkgload11b0251da3c23/BPCells.so: undefined symbol: _ZTVN7BPCells14LinearResidualE
```
The file paths in `src/` were checked and nothing abnormal was found. The `src/matrixTransforms/LinearResidual.o` was not created. Maybe I overlooked something? 

Do you have idea where the error could come from? Thanks for any advice.

**Comment by bnprks** [comment]
Sure, this one should be pretty easy -- you just need to add the `.o` file you want made into the list present in the `Makevars.in` file. Ultimately that gets processed into the `Makevars` file at build time and then used to set what files R should compile.

-Ben

**Comment by ycli1995** [comment]
Thank you! It can be normally compiled after I modified the `Makevars.in` file!

For the usage of `loadZero` and `loadZeroSubtracted` method, not pretty sure that I got the right understanding. I'd check out the existing examples for `MatrixTransformDense` as you advised.

Since the original problem has been solved, I'll close the issue for the moment.
