### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by gevro** [bnprks/BPCells#136]
Latest version of R and BPCells on linux x64

** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘BPCells’ in dyn.load(file, DLLpath = DLLpath, ...):
unable to load shared object ... R/library/00LOCK-BPCells/00new/BPCells/libs/BPCells.so':
R/library/00LOCK-BPCells/00new/BPCells/libs/BPCells.so: undefined symbol: H5Treclaim
Error: loading failed
Execution halted
ERROR: loading failed

**Comment by immanuelazn** [comment]
Hi gevro,
Thanks for reaching out!
The error you linked indicates that H5Treclaim is not available, which is part of HDF5.  BPCells relies on having HDF5 installed.  Could you confirm that you have HDF5 installed, and whether your version of HDF5 is up to date?

If not, to install, you can first run:  sudo apt-get install libhdf5-dev to get the latest HDF5 .  Then perhaps retry installing BPCells.

If it indeed installed, there is probably something wrong with the library search with finding `libhdf5.so`.  If this is the case, could you try providing some additional debug info from running:

```
Sys.setenv(BPCELLS_DEBUG_INSTALL=TRUE)
remotes::install_github("bnprks/BPCells/r")
```
and providing the outputs here?

Best,

Immanuel

**Comment by gevro** [comment]
How do I install that in a conda environment?

**Comment by immanuelazn** [comment]
Hi gevro,

Thanks for the question!
Being on a conda environment requires using conda to install hdf5 instead rather than your default linux installer, as it will likely use R specific to your conda environment.  Try the following:
`conda install conda-forge::hdf5`

**Comment by gevro** [comment]
Works now, thanks!
