### ISSUE TITLE
Installation issue (Amazon Linux 2, hdf5 from source)

### ISSUE THREAD

**Issue by bnprks** [bnprks/BPCells#16]
[Issue split out from a comment on another issue]

Same here, i'm running into the same issue as @sanderslhc I installed hdf5 from source and can successfully run `h5cc -showconfig` and it's in path!  During the install process it runs `pkg-config hdf5 --cflags --libs` to validate that hdf5 exists and it's not finding it, so it's suggesting we find a non-existing file: `hdf5.pc` and add it to the PKG_CONFIG_PATH. @bnprks  isn't there a better way to validate hdf5 exists like using `h5cc`?
Also i'm using `Amazon Linux 2` on an EC2 it's closer to centos and rhel than to ubuntu.
![Screenshot 2023-04-06 at 7 24 14 PM](https://user-images.githubusercontent.com/105394080/230528045-e19c5d56-f067-40d8-a375-5d121afd9b86.png)

_Originally posted by @steklemichael in https://github.com/bnprks/BPCells/issues/15#issuecomment-1499863781_

**Comment by bnprks** [comment]
Hi @stekelmichael, I've split your issue out here because I think it's a different root cause than the issue you commented on (hdf5 installation from source on linux vs hdf5 from conda on an unknown OS).

My recommendation for an easy option on Linux is to install hdf5 through your OS's package manager, rather than installing hdf5 from source. It appears that Amazon Linux uses `yum` for installation, so probably the installation line from the README that will work for you is: `yum install hdf5-devel` (you may need to add `sudo` at the start of that). If you install through the system package manager, then `pkg-config` should be able to find hdf5 automatically as it will come with the necessary `hdf5.pc` file. 

I'm not sure exactly what's available through the Amazon Linux 2 default package repository, so you may need to investigate the [Amazon docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-ami-basics.html#package-repository) some if you run in to issues initially

Alternatively, you can manually install hdf5 to the standard location for your OS (usually `/usr/lib` or something like that), such that you are able to compile [tools/h5write.c](https://github.com/bnprks/BPCells/blob/main/tools/h5write.c) with the command: `gcc h5write.c -lhdf5 -o h5write`. This requires a bit more know-how on your part, but is an option if you have a strong reason that you can't use the hdf5 package that is likely available through your linux distribution

**Comment by steklemichael** [comment]
So initally we had packages that required newer versions of HDF5 than what was provided by EPEL (newer than 1.8.12) luckily I was able to find rpm of slightly newer versions. Currently got HDF5 v1.8.13 installed but I got the same error with earlier (default yum) option too.  When I tried to install the package.
![Screenshot 2023-04-09 at 5 43 24 PM](https://user-images.githubusercontent.com/105394080/230804720-1150d53d-a831-48de-9a4c-b83102b2edd5.png)

**Comment by steklemichael** [comment]
actually, I figured out the solution, which was to update my version of GCC [here](https://stackoverflow.com/questions/61165009/how-to-install-devtoolset-8-gcc-8-on-amazon-linux-2) are the steps I followed, hope others find them helpful.

**Comment by bnprks** [comment]
Thanks for following up with what worked for you, glad it's running now

**Comment by Zepeng-Mu** [comment]
I'm using gcc 11.2.0. I'm wondering which version should I update to?

**Comment by bnprks** [comment]
@Zepeng-Mu Is your question related to this issue about installation on Amazon Linux 2? 

To my knowledge gcc 11.2.0 should be plenty new enough to have the C++17 features required by BPCells (>9.1 is recommended). Most people have installation issues related to the hdf5 library rather than gcc version, which on Linux is usually easy to handle by installing through your distro's package manager. The hdf5 library detection logic has also been a bit improved since this issue was filed, by taking advantage of the compiler flags suggested by `h5cc -showconfig` when relevant.

If you're using Amazon Linux 2 could you provide a bit more information on your current issue in this thread? If you're on a different operating system you might file a new issue if there's no existing issue that answers your question.

**Comment by Zepeng-Mu** [comment]
Hi, thanks for the quick reply. My problem is not about Amazon Linux, but on the school's HPC system. Specifically, I'm using my own conda environment and have hdf5 installed through mamba. I think I have some other packages like ArchR that also uses hdf5 and they work just fine. I read a lot issues related to hdf5 in installation but none of them really solves the problem. Since I'm using the HPC system, I cannot use tools like yum because I do not have root privilege. My `h5cc -showconfig` looks like this

```
╰─$ h5cc -showconfig
            SUMMARY OF THE HDF5 CONFIGURATION
            =================================

General Information:
-------------------
                   HDF5 Version: 1.12.2
                  Configured on: Wed Jul 27 14:30:13 UTC 2022
                  Configured by: conda@4c7d15d64276
                    Host system: x86_64-conda-linux-gnu
              Uname information: Linux 4c7d15d64276 5.15.0-1014-azure #17~20.04.1-Ubuntu SMP Thu Jun 23 20:01:51 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
                       Byte sex: little-endian
             Installation point: /scratch/midway3/zepengmu/miniconda3/envs/R42

Compiling Options:
------------------
                     Build Mode: production
              Debugging Symbols: no
                        Asserts: no
                      Profiling: no
             Optimization Level: high

Linking Options:
----------------
                      Libraries: static, shared
  Statically Linked Executables: 
                        LDFLAGS: -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,--allow-shlib-undefined -Wl,-rpath,/scratch/midway3/zepengmu/miniconda3/envs/R42/lib -Wl,-rpath-link,/scratch/midway3/zepengmu/miniconda3/envs/R42/lib -L/scratch/midway3/zepengmu/miniconda3/envs/R42/lib
                     H5_LDFLAGS: 
                     AM_LDFLAGS:  -L/scratch/midway3/zepengmu/miniconda3/envs/R42/lib
                Extra libraries: -lcrypto -lcurl -lrt -lpthread -lz -ldl -lm 
                       Archiver: /home/conda/feedstock_root/build_artifacts/hdf5_split_1658932061303/_build_env/bin/x86_64-conda-linux-gnu-ar
                       AR_FLAGS: cr
                         Ranlib: /home/conda/feedstock_root/build_artifacts/hdf5_split_1658932061303/_build_env/bin/x86_64-conda-linux-gnu-ranlib

Languages:
----------
                              C: yes
                     C Compiler: /home/conda/feedstock_root/build_artifacts/hdf5_split_1658932061303/_build_env/bin/x86_64-conda-linux-gnu-cc
                       CPPFLAGS: -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /scratch/midway3/zepengmu/miniconda3/envs/R42/include
                    H5_CPPFLAGS: -D_GNU_SOURCE -D_POSIX_C_SOURCE=200809L   -DNDEBUG -UH5_DEBUG_API
                    AM_CPPFLAGS:  -I/scratch/midway3/zepengmu/miniconda3/envs/R42/include
                        C Flags: -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /scratch/midway3/zepengmu/miniconda3/envs/R42/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/hdf5_split_1658932061303/work=/usr/local/src/conda/hdf5_split-1.12.2 -fdebug-prefix-map=/scratch/midway3/zepengmu/miniconda3/envs/R42=/usr/local/src/conda-prefix
                     H5 C Flags:  -std=c99  -Wall -Wcast-qual -Wconversion -Wextra -Wfloat-equal -Wformat=2 -Winit-self -Winvalid-pch -Wmissing-include-dirs -Wshadow -Wundef -Wwrite-strings -pedantic -Wno-c++-compat -Wlarger-than=2560 -Wlogical-op -Wframe-larger-than=16384 -Wpacked-bitfield-compat -Wsync-nand -Wstrict-overflow=5 -Wno-unsuffixed-float-constants -Wdouble-promotion -Wtrampolines -Wstack-usage=8192 -Wmaybe-uninitialized -Wdate-time -Warray-bounds=2 -Wc99-c11-compat -Wduplicated-cond -Whsa -Wnormalized -Wnull-dereference -Wunused-const-variable -Walloca -Walloc-zero -Wduplicated-branches -Wformat-overflow=2 -Wformat-truncation=1 -Wrestrict -Wattribute-alias -Wcast-align=strict -Wshift-overflow=2 -Wattribute-alias=2 -Wmissing-profile -Wc11-c2x-compat -fstdarg-opt -fdiagnostics-urls=never -fno-diagnostics-color -s  -Wbad-function-cast -Wimplicit-function-declaration -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpacked -Wpointer-sign -Wpointer-to-int-cast -Wint-to-pointer-cast -Wredundant-decls -Wstrict-prototypes -Wswitch -Wunused-function -Wunused-variable -Wunused-parameter -Wcast-align -Wunused-but-set-variable -Wformat -Wincompatible-pointer-types -Wint-conversion -Wshadow -Wcast-function-type -Wmaybe-uninitialized -Wno-aggregate-return -Wno-inline -Wno-missing-format-attribute -Wno-missing-noreturn -Wno-overlength-strings -Wno-jump-misses-init -Wno-suggest-attribute=const -Wno-suggest-attribute=noreturn -Wno-suggest-attribute=pure -Wno-suggest-attribute=format -Wno-suggest-attribute=cold -Wno-suggest-attribute=malloc -O3
                     AM C Flags: 
               Shared C Library: yes
               Static C Library: yes


                        Fortran: yes
               Fortran Compiler: /home/conda/feedstock_root/build_artifacts/hdf5_split_1658932061303/_build_env/bin/x86_64-conda-linux-gnu-gfortran
                  Fortran Flags: 
               H5 Fortran Flags:  -std=f2008  -Waliasing -Wall -Wcharacter-truncation -Wextra -Wimplicit-interface -Wsurprising -Wunderflow -pedantic -Warray-temporaries -Wintrinsics-std -Wimplicit-procedure -Wreal-q-constant -Wfunction-elimination -Wrealloc-lhs -Wrealloc-lhs-all -Wno-c-binding-type -Winteger-division -Wfrontend-loop-interchange  -fdiagnostics-urls=never -fno-diagnostics-color -s -O3
               AM Fortran Flags: 
         Shared Fortran Library: yes
         Static Fortran Library: yes

                            C++: yes
                   C++ Compiler: /home/conda/feedstock_root/build_artifacts/hdf5_split_1658932061303/_build_env/bin/x86_64-conda-linux-gnu-c++
                      C++ Flags: -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /scratch/midway3/zepengmu/miniconda3/envs/R42/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/hdf5_split_1658932061303/work=/usr/local/src/conda/hdf5_split-1.12.2 -fdebug-prefix-map=/scratch/midway3/zepengmu/miniconda3/envs/R42=/usr/local/src/conda-prefix
                   H5 C++ Flags:   -Wall -Wcast-qual -Wconversion -Wctor-dtor-privacy -Weffc++ -Wextra -Wfloat-equal -Wformat=2 -Winit-self -Winvalid-pch -Wmissing-include-dirs -Wnon-virtual-dtor -Wold-style-cast -Woverloaded-virtual -Wreorder -Wshadow -Wsign-promo -Wundef -Wwrite-strings -pedantic -Wlarger-than=2560 -Wlogical-op -Wframe-larger-than=16384 -Wpacked-bitfield-compat -Wsync-nand -Wstrict-overflow=5 -Wdouble-promotion -Wtrampolines -Wstack-usage=8192 -Wmaybe-uninitialized -Wdate-time -Wopenmp-simd -Warray-bounds=2 -Wduplicated-cond -Whsa -Wnormalized -Wnull-dereference -Wunused-const-variable -Walloca -Walloc-zero -Wduplicated-branches -Wformat-overflow=2 -Wformat-truncation=1 -Wrestrict -Wattribute-alias -Wcast-align=strict -Wshift-overflow=2 -Wattribute-alias=2 -Wmissing-profile -Wno-deprecated-copy -fstdarg-opt -fdiagnostics-urls=never -fno-diagnostics-color -s  -Wcast-align -Wmissing-declarations -Wpacked -Wredundant-decls -Wswitch -Wunused-but-set-variable -Wunused-function -Wunused-variable -Wunused-parameter -Wshadow -O3
                   AM C++ Flags: 
             Shared C++ Library: yes
             Static C++ Library: yes

                           Java: no


Features:
---------
                     Parallel HDF5: no
  Parallel Filtered Dataset Writes: no
                Large Parallel I/O: no
                High-level library: yes
Dimension scales w/ new references: no
                  Build HDF5 Tests: yes
                  Build HDF5 Tools: yes
                      Threadsafety: yes
               Default API mapping: v112
    With deprecated public symbols: yes
            I/O filters (external): deflate(zlib)
                               MPE: no
                     Map (H5M) API: no
                        Direct VFD: yes
                        Mirror VFD: no
                (Read-Only) S3 VFD: yes
              (Read-Only) HDFS VFD: no
                           dmalloc: no
    Packages w/ extra debug output: none
                       API tracing: no
              Using memory checker: yes
   Memory allocation sanity checks: no
            Function stack tracing: no
                  Use file locking: best-effort
         Strict file format checks: no
      Optimization instrumentation: no
```

**Comment by bnprks** [comment]
Hi @Zepeng-Mu, it sounds like your question is not related to this issue thread's topic. Please do not post questions in this issue thread that are not specifically related to the listed topic. (this helps keep issues organized and searchable). Also, when you do have to post a long block of text, try formatting it as a [collapsible section](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections) so things are easier to skim for myself and others.

I'll repeat my request from my previous comment -- please search to make sure that no existing issue answers your question, and if not you can file a new issue with an appropriate topic.

When you file that issue, please include the full context of what OS + environment you're working on, as well as the error message you're getting when installing BPCells and what you've already tried to do to fix it.

**Comment by Zepeng-Mu** [comment]
OK, turned out that when I used debug mode to install BPCells, I got something like `Undefined reference to memcpy@GLIBC_2.14]` during the config steps for hdf5. A quick google revealed that I should update `sysroot_linux-64`. And this solved my issue.

Now I realized that my problem might be unrelated to the issue here, although we both initially got `Unable to detect libhdf5`.
