### ISSUE TITLE
export rbind2 and cbind2 methods?

### ISSUE THREAD

**Issue by brgew** [bnprks/BPCells#25]
Hi Ben,

I hope that you haven't answered this question already.

I am testing some matrix combining code and I see errors telling me that `BPCells::rbind2` and `BPCells::cbind2` are not exported. I modified the BPCells/R/matrix.R code to export the methods and our code works now. Am I messing up yet again? (I hope not.)

If it seems reasonable to add these exports, I can create a pull request with the modifications.

I appreciate your patience with me.

Ever grateful,
Brent

**Comment by bnprks** [comment]
The S4 generics are definitely tricky so it's possible this requires an export, though I didn't think it would.

`rbind2` and `cbind2` are generics from the build-in `methods` package, which BPCells provides specialized implementations for when using IterableMatrix objects. So my expectation would be that using `rbind2` or `methods::rbind2` would work, and `BPCells::rbind2` probably wouldn't.

If that doesn't work a pull request would be fine, though I'd want to confirm the problem for myself before throwing in the export annotation -- if you could provide some short example code that hits the issues that would be nice.

**Comment by bnprks** [comment]
Yeah, I've seen those docs and I agree with you on that last bullet point. 

Weirdly, this does not match with some of my experimenting. For instance, this works fine for me:
```R
library(BPCells)
m <- matrix(1:12, nrow=3)
m <- as(m, "dgCMatrix")
m <- as(m, "IterableMatrix")
m2 <- rbind2(m, m)
m3 <- cbind2(m, m)
```

But maybe the issue only pops up when in use in another package which wouldn't have the `library(BPCells)` call. I'm basically just wanting to double-check you weren't prefixing your calls with `BPCells::rbind2`, and that both `rbind2` and `methods::rbind2` fail for you in the same context. 

If that all still fails, then that's a good catch you've made and I should learn to trust the docs more :) No need to make a perfectly exhaustive example if it's only a problem within a package, just seeing the call site and error message are likely enough for me to reproduce.

**Comment by bnprks** [comment]
Hi Brent,

We're all learning here so no need to be self-conscious :). I think we're getting to territory that's at the edge of my own knowledge (but hopefully just barely within). In general, I'd highly recommend the Advanced R online book for a reference on S3 and S4 generics: [link](https://adv-r.hadley.nz/s4.html#s4-generics)

If I change your last line to:
```R
cm1 <- methods::rbind2(bpm1, bpm2)
```
then it works for me with no problem.

The distinction here is that the function (rbind2) is not defined in BPCells but rather the methods package(via `setGeneric()` ). What is defined in BPCells is a method, which specifies what should happen when rbind2 is called with IterableMatrix objects (via `setMethod()`).

Now, I don't know when/where R picks up on the fact that BPCells has registered a specialization of rbind2, but it appears to not rely on having called `library(BPCells)`:
```R
v1 <- c(1,2,3,4,5,6)
m1 <- matrix(v1,nrow=2)
bpm1 <- BPCells::write_matrix_memory(as(m1, 'dgCMatrix'))

v2 <- c(7,8,9,10,11,12)
m2 <- matrix(v2,nrow=2)
bpm2 <- BPCells::write_matrix_memory(as(m2, 'dgCMatrix'))

cm1 <- rbind2(bpm1, bpm2)
```
The above runs for me with no error in a fresh R terminal
