### ISSUE TITLE
Converting ArchR project to BPCells 

### ISSUE THREAD

**Issue by JLemvig** [bnprks/BPCells#32]
Hi @bnprks, 

I am excited to try BPCells on my current ATACseq project but I am having issues migrating my data from ArchR.

My current project contains 500.000 cells across 100 samples, and while extracting the fragments of a single sample and converting them to BPCells fragments works as expected, I am running into trouble when I try to scale it to the full project exceeding the R vector limitations combining the samples.

I can see from the [Seurat v5 tutorial on BPCells](https://satijalab.org/seurat/articles/seurat5_bpcells_interaction_vignette.html#load-data-from-multiple-h5ad-files) that they are creating individual matrices and merging them when creating the Seurat object, but i am uncertain if this would work with ATACseq.

What would be the best approach to converting my ArchR project to BPCells?

Best regards
Jonas

**Comment by bnprks** [comment]
Closing this for now, but feel free to reply/re-open the issue if you have further questions in this area

**Comment by plbngl** [comment]
Hello - just a quick followup on this -- when combining matrices and fragments objects with cbind and c, respectively, it assumes the barcodes names have been renamed with barcode+sample to make them unique? is there a way to do it using bpcells? thank you!

**Comment by plbngl** [comment]
sorry, I just saw the prefix_cell_name() function 
https://bnprks.github.io/BPCells/reference/prefix_cell_names.html
