### ISSUE TITLE
Unsuccessful installation on Windows

### ISSUE THREAD

**Issue by bykovam** [bnprks/BPCells#37]
I'm trying to install BPCells to follow this Seurat tutorial(https://satijalab.org/seurat/articles/seurat5_bpcells_interaction_vignette.html), and I'm receiving this console readout:

Installing package into ‘C:/Users/BYKOVAM/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
* installing *source* package 'BPCells' ...
** using staged installation
Testing hdf5 by compiling example program...
C:\rtools42/x86_64-w64-mingw32.static.posix/bin/ld.exe: cannot find -lsz
collect2.exe: error: ld returned 1 exit status

Unable to locate libhdf5. Please install manually or edit compiler flags.
ERROR: configuration failed for package 'BPCells'
* removing 'C:/Users/BYKOVAM/AppData/Local/R/win-library/4.2/BPCells'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/BYKOVAM/AppData/Local/Temp/RtmpERPVuP/file6d45421204a8e/BPCells_0.1.0.tar.gz’ had non-zero exit status

I'm installing this in Rstudio version 2022.07.2 Build 576 on a Windows 10 laptop

**Comment by bnprks** [comment]
Thanks for the question. This seems related to #9 and #34. 

I think the most important consideration here is the version of Rtools. Personally, I'm using Windows 11 with Rtools4.3 as installed from the [CRAN website](https://cran.r-project.org/bin/windows/Rtools/rtools43/rtools.html). 

I haven't quite been able to reproduce your specific issue, even when I tried installing R version 4.2 with RTools 4.2 on a Windows 10 laptop. However, I've made a branch with a fix that I *think* should address your current issue, though it might just fail differently. 

In the event that this test fix doesn't fix your issue it might require a bit of slow back-and-forth to get to a working fix, but I'd appreciate it if you're willing to help test this out as other people have had this bug but I haven't been able to reproduce it myself yet.

At any rate, to test out the new branch, you'd run `remotes::install_github("bnprks/BPCells", ref="windows-install-fix")`, then let me know what (if any) error messages you get after trying to install with it.

**Comment by bykovam** [comment]
Thanks so much for your help! I'll test it out and see if it fixes the issue

**Comment by bykovam** [comment]
Thanks so much! I installed it, and it worked great, no issues seen!

**Comment by bnprks** [comment]
Great! I just merged those changes into main in commit a3987d1f74c707e45e464adaae07f8d9541c3ef5, so hopefully that fixes it for future Windows users with your specific setup.
